#!/bin/bash
set -u

export CERTDIR=${CERTDIR:-"./certs"}
export IP=${IP:-localhost}

echo "################################### cluster 1"
arangosync get status \
  --master.endpoint=https://${IP}:8837 \
  --auth.keyfile=${CERTDIR}/client-auth-ca.keyfile \
  --verbose

echo "################################### cluster 2"
arangosync get status \
  --master.endpoint=https://${IP}:9937 \
  --auth.keyfile=${CERTDIR}/client-auth-ca.keyfile \
  --verbose
