#!/bin/bash

export CERTDIR=${CERTDIR:-"./certs"}
export IP=${IP:-localhost}

mkdir -p ${CERTDIR}

# Create TLS certificates
arangodb create tls ca --cert=${CERTDIR}/tls-ca.crt --key=${CERTDIR}/tls-ca.key
arangodb create tls keyfile --cacert=${CERTDIR}/tls-ca.crt --cakey=${CERTDIR}/tls-ca.key --keyfile=${CERTDIR}/cluster1-tls.keyfile --host=${IP} --host=localhost
arangodb create tls keyfile --cacert=${CERTDIR}/tls-ca.crt --cakey=${CERTDIR}/tls-ca.key --keyfile=${CERTDIR}/cluster2-tls.keyfile --host=${IP} --host=localhost

# Create client authentication certificates
arangodb create client-auth ca --cert=${CERTDIR}/client-auth-ca.crt --key=${CERTDIR}/client-auth-ca.key
arangodb create client-auth keyfile --cacert=${CERTDIR}/client-auth-ca.crt --cakey=${CERTDIR}/client-auth-ca.key --keyfile=${CERTDIR}/client-auth-ca.keyfile

# Create JWT secrets
arangodb create jwt-secret --secret=${CERTDIR}/cluster1-syncmaster.jwtsecret
arangodb create jwt-secret --secret=${CERTDIR}/cluster1-arangodb.jwtsecret
arangodb create jwt-secret --secret=${CERTDIR}/cluster2-syncmaster.jwtsecret
arangodb create jwt-secret --secret=${CERTDIR}/cluster2-arangodb.jwtsecret
