#!/bin/bash
set -u

export CERTDIR=${CERTDIR:-"./certs"}
export IP=${IP:-localhost}
data="$HOME/release-test-data/dc2dc-cluster1"

ferr() {
    echo "$*"
    exit 1
}

mkdir -p "$data" || ferr "failed to create data dir"
jwt_secret=${CERTDIR}/cluster1-arangodb.jwtsecret
server_keyfile=${CERTDIR}/cluster1-tls.keyfile
server_ca=${CERTDIR}/client-auth-ca.crt
master_jwt_secret=${CERTDIR}/cluster1-syncmaster.jwtsecret

for f in "$jwt_secret" "$server_keyfile" "$server_ca" "$master_jwt_secret"; do
    [[ -f "$f" ]] || ferr "file not present $f"
done

exec arangodb --starter.data-dir="$data" \
              --starter.port=8833 \
              --starter.sync \
              --starter.local \
              --auth.jwt-secret="$jwt_secret" \
              --sync.server.keyfile="$server_keyfile" \
              --sync.server.client-cafile="$server_ca" \
              --sync.master.jwt-secret="$master_jwt_secret" \
              --starter.address="${IP}"
