#!/bin/bash
set -u

export CERTDIR=${CERTDIR:-"./certs"}
export IP=${IP:-localhost}

arangosync stop sync \
  --auth.keyfile=${CERTDIR}/client-auth-ca.keyfile \
  --master.endpoint=https://${IP}:8837
