#!/bin/bash

data="$HOME/release-test-data/cluster-node4"
mkdir -p "$data"
exec arangodb --starter.data-dir="$data" \
              --starter.join=localhost:8833 \
              --starter.unique-port-offsets=true \
              --server.storage-engine=rocksdb
