#!/bin/bash

data="$HOME/release-test-data/cluster-node2"
mkdir -p "$data"
exec arangodb --starter.data-dir="$data" \
              --starter.join=localhost:8833 \
              --server.storage-engine=rocksdb \
              --auth.jwt-secret=./jwt-secret
