#!/bin/bash
set -u

. config.bash

edition=$1     # enterprise community
auth=$2        # no-auth
server_type=$3 # agent dba starter
number=$4      # 1 2 3

echo "configuration"
echo "edition:     $edition"
echo "auth:        $auth"
echo "server_type: $server_type"
echo "number:      $number"


cmd=(
    "docker" "run" "--rm"
)

if [[ $edition == "enterprise" ]]; then
    cmd+=( "-e" "ARANGO_LICENSE_KEY=${enterprise_key}" )
else
    echo "not enterprise"
    exit 1
fi

if [[ $auth == "no-auth" ]]; then
    cmd+=( "-e" "ARANGO_NO_AUTH=1 " )
else
    cmd+=( "-e" "ARANGO_ROOT_PASSWORD=$password"
           "-v" "$secret_dir:/secret"
    )
fi
case "${server_type}-${number}" in
    starter-1)
        portmap="10000:8528"
    ;;
    starter-1)
        portmap="11000:9528"
    ;;
    starter-2)
        portmap="12000:10528"
    ;;
    manual-agent-3)
        port=5003
    ;;
    manual-db-1)
        port=6001
    ;;
    manual-db-2)
        port=6002
    ;;
    manual-db-3)
        port=6003
    ;;
    *)
        echo "mode server_type number combination not supported - ${mode}-${server_type}-${number}"
    ;;
esac


if [[ -n "portmap" ]]; then
    cmd+=( "-p" "$portmap" )
else
    cmd+=( "--net" "host" )
fi

case "${server_type}" in
    starter)
        cmd+=(
           '-v' '/var/run/docker.sock:/var/run/docker.sock'
           'arangodb/arangodb-starter'
           '--starter.address=127.0.0.1'
           "--docker.image=$image"
           '--starter.mode' 'activefailover'
        )

        if (( number > 1 )); then
            cmd+=( "--starter.join" "127.0.0.1:10000" )
        fi
    ;;
    agent)
        cmd+=(
            "$image" 'arangod'
            "--server.endpoint" "tcp://0.0.0.0:$port"
            "--agency.my-address=tcp://127.0.0.1:$port"
            "--agency.activate" "true"
            "--agency.size" "3"
            "--agency.endpoint" "tcp://127.0.0.1:5001"
            "--agency.supervision" "true"
            '--database.directory' "af-manual-${server_type}-${number}"
        )
    ;;
    db)
        cmd+=(
            "$image" 'arangod'
            "--server.endpoint" "tcp://0.0.0.0:$port"
            "--cluster.my-address=tcp://127.0.0.1:$port"
            "--cluster.my-role" "SINGLE"
            "--cluster.agency-endpoint" "tcp://127.0.0.1:5001"
            "--cluster.agency-endpoint" "tcp://127.0.0.1:5002"
            "--cluster.agency-endpoint" "tcp://127.0.0.1:5003"
            "--replication.automatic-failover" "true"
            '--database.directory' "af-manual-${server_type}-${number}"
        )
    ;;
esac

if [[ $auth == "no-auth" ]]; then
    echo "no secret to add"
else
    auth_flag="--server.jwt-secret-keyfile"
    if [[ $server_type == "starter" ]]; then
        auth_flag="--auth.jwt-secret"
    fi
    cmd+=( "$auth_flag=/secret/${secret_file##*/}" )
fi

echo "running: ${cmd[@]}"
sleep 3
"${cmd[@]}"
