#!/bin/bash

data="$HOME/release-test-data/active-failover-node2"
mkdir -p "$data"
exec arangodb --starter.data-dir="$data" \
              --starter.join=localhost:8833 \
              --starter.unique-port-offsets=true \
              --starter.mode=activefailover
