#!/bin/bash

data="$HOME/release-test-data/active-failover-node3"
mkdir -p "$data"
exec arangodb --starter.data-dir="$data" \
              --starter.join localhost \
              --starter.mode=activefailover
